# Generated by Django 3.1.3 on 2021-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
